# Generated by Django 5.0.6 on 2024-07-06 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('commander', models.CharField(max_length=20)),
                ('power_level', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ImageField(null=True, upload_to='trainers/')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('toughness', models.IntegerField(blank=True, null=True)),
                ('card_type', models.CharField(choices=[('creature', 'Creature'), ('instant', 'Instant'), ('sorcery', 'Sorcery'), ('artifact', 'Artifact'), ('enchantment', 'Enchantment'), ('battle', 'Battle'), ('planeswalker', 'Planeswalker')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ImageField(null=True, upload_to='cards/')),
                ('points', models.IntegerField(blank=True, null=True)),
                ('deck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alex.deck')),
            ],
        ),
    ]
