# Generated by Django 5.0.6 on 2024-07-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deck',
            name='commander',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
