# Generated by Django 5.0.6 on 2024-07-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alex', '0003_deck_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
